import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createStore } from './store.mjs';
import { createPublisher, findGit } from './publisher.mjs';
import { build } from './build.mjs';

test('publishing exports only public posts, preserves unrelated work, archives, restores, and retries offline changes', async t => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'xingyu-publisher-test-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const git = await findGit();
  const run = async (cwd, ...args) => (await promisify(execFile)(git, args, { cwd })).stdout.trim();
  const repoRoot = path.join(directory, 'author');
  const remote = path.join(directory, 'remote.git');
  await run(directory, 'init', '--bare', '--initial-branch=master', remote);
  await run(directory, 'init', '--initial-branch=master', repoRoot);
  await run(repoRoot, 'config', 'user.name', 'Blog Test');
  await run(repoRoot, 'config', 'user.email', 'blog-test@example.invalid');
  const publicDirectory = path.join(repoRoot, 'blog/_content');
  await mkdir(publicDirectory, { recursive: true });
  await writeFile(path.join(publicDirectory, 'legacy.md'), '---\ntitle: Legacy\nslug: legacy\ndate: "2026-09-01"\n---\n\nOriginal public writing.');
  await writeFile(path.join(repoRoot, 'blog/handwritten.html'), 'Keep this standalone page.');
  await writeFile(path.join(repoRoot, 'index.html'), 'Original homepage.');
  await build({ root: path.join(repoRoot, 'blog') });
  await run(repoRoot, 'add', '.');
  await run(repoRoot, 'commit', '-m', 'Initial site');
  await run(repoRoot, 'remote', 'add', 'origin', remote);
  await run(repoRoot, 'push', '-u', 'origin', 'master');
  // None of these unpushed commits, staged edits, or loose files may be published.
  await writeFile(path.join(repoRoot, 'unrelated.txt'), 'Unpushed code change.');
  await run(repoRoot, 'add', 'unrelated.txt');
  await run(repoRoot, 'commit', '-m', 'Unrelated local commit');
  await writeFile(path.join(repoRoot, 'index.html'), 'An unfinished homepage edit.');
  await run(repoRoot, 'add', 'index.html');
  await writeFile(path.join(repoRoot, 'private-loose.txt'), 'Untracked private text.');
  const originalStatus = await run(repoRoot, 'status', '--porcelain');
  const originalHead = await run(repoRoot, 'rev-parse', 'HEAD');
  const library = path.join(directory, 'private-library');
  const store = createStore({ directory: library, publicDirectory });
  await store.save({ title: 'Secret draft', body: 'DRAFT_SECRET' });
  await store.save({ title: 'Secret private', body: 'PRIVATE_SECRET' }, 'private');
  const publicPost = await store.save({ title: 'Public essay', body: 'Visible writing and $x^2$.' }, 'public');
  const publisher = createPublisher({ repoRoot, directory: library, store });
  assert.equal((await publisher.sync()).state, 'sent');
  const show = file => run(remote, 'show', `master:${file}`);
  assert.match(await show('blog/index.html'), /Public essay/);
  assert.match(await show('blog/public-essay.html'), /Visible writing/);
  assert.match(await show('blog/_content/public-essay.md'), /Visible writing/);
  assert.doesNotMatch(await show('blog/index.html'), /Secret draft|Secret private/);
  assert.doesNotMatch(await run(remote, 'ls-tree', '-r', '--name-only', 'master'), /secret|private|drafts|\.admin-password|unrelated/);
  assert.equal(await show('index.html'), 'Original homepage.');
  assert.equal(await show('blog/handwritten.html'), 'Keep this standalone page.');
  assert.equal(await run(repoRoot, 'status', '--porcelain'), originalStatus);
  assert.equal(await run(repoRoot, 'rev-parse', 'HEAD'), originalHead);
  const archived = await store.archive(publicPost);
  const legacy = (await store.list()).find(post => post.slug === 'legacy');
  await store.archive(legacy);
  assert.equal((await publisher.sync()).state, 'sent');
  await assert.rejects(show('blog/public-essay.html'));
  await assert.rejects(show('blog/_content/public-essay.md'));
  await assert.rejects(show('blog/legacy.html'));
  assert.match(await readFile(path.join(library, 'archive/public-essay/post.md'), 'utf8'), /Visible writing/);
  await store.restore(archived);
  assert.equal((await publisher.sync()).state, 'sent');
  assert.match(await show('blog/public-essay.html'), /Visible writing/);
  await assert.rejects(show('blog/legacy.html'));
  const before = await run(remote, 'rev-parse', 'master');
  assert.equal((await publisher.sync()).state, 'sent');
  assert.equal(await run(remote, 'rev-parse', 'master'), before, 'retrying a successful publish must not duplicate commits');
  await run(repoRoot, 'remote', 'set-url', 'origin', path.join(directory, 'offline.git'));
  const offline = await store.save({ title: 'Offline public', body: 'Saved while offline.' }, 'public');
  assert.equal((await publisher.sync()).state, 'pending');
  assert.equal((await publisher.status()).state, 'pending');
  assert.equal((await store.list()).find(post => post.slug === offline.slug).readOnly, true);
  await run(repoRoot, 'remote', 'set-url', 'origin', remote);
  const restarted = createPublisher({ repoRoot, directory: library, store });
  assert.equal((await restarted.status()).state, 'pending');
  assert.equal((await restarted.sync()).state, 'sent');
  assert.match(await show('blog/offline-public.html'), /Saved while offline/);
  assert.equal(await run(repoRoot, 'status', '--porcelain'), originalStatus);
});
