import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, readFile, access } from 'node:fs/promises';
import { once } from 'node:events';
import path from 'node:path';
import os from 'node:os';
import { blogRoot } from './build.mjs';

test('same-site admin authenticates, protects drafts and private posts, publishes immutable posts, and archives deletions', async t => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'xingyu-admin-test-'));
  const port = 19000 + Math.floor(Math.random() * 1000);
  const server = spawn(process.execPath, [path.join(blogRoot, 'scripts/writer.mjs')], { env: { ...process.env, BLOG_LIBRARY_DIR: directory, BLOG_WRITER_PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
  t.after(() => server.kill());
  await Promise.race([once(server.stdout, 'data'), once(server, 'exit').then(() => { throw new Error('Server exited before listening.'); }), new Promise((_, reject) => { const timeout = setTimeout(() => reject(new Error('Startup timed out.')), 5000); timeout.unref(); })]);
  const origin = `http://127.0.0.1:${port}`;
  const anonymous = await fetch(`${origin}/write`, { redirect: 'manual' });
  assert.equal(anonymous.status, 303); assert.equal(anonymous.headers.get('location'), '/admin');
  assert.equal((await fetch(`${origin}/api/posts`)).status, 401);
  assert.equal((await fetch(`${origin}/api/auth`)).headers.get('set-cookie'), null);
  const challenge = await fetch(`${origin}/api/auth?login=1`);
  const session = await challenge.json(); assert.equal(session.setup, true);
  const headers = { 'Content-Type': 'application/json', 'X-Writing-Token': session.token, Cookie: challenge.headers.get('set-cookie').split(';')[0] };
  const login = await fetch(`${origin}/api/login`, { method: 'POST', headers, body: JSON.stringify({ password: 'Temporary test password 123!' }) });
  assert.equal(login.status, 200);
  const cookie = login.headers.getSetCookie()[0]; assert.match(cookie, /HttpOnly/); assert.match(cookie, /SameSite=Strict/);
  headers.Cookie = cookie.split(';')[0];
  headers['X-Writing-Token'] = (await fetch(`${origin}/api/auth`, { headers }).then(r => r.json())).token;
  for (const route of ['/admin', '/write']) {
    const redirect = await fetch(origin + route, { headers, redirect: 'manual' });
    assert.equal(redirect.status, 303); assert.equal(redirect.headers.get('location'), '/blog/');
  }
  const admin = await fetch(`${origin}/blog/`, { headers });
  assert.equal(admin.status, 200); assert.equal(admin.headers.get('x-robots-tag'), 'noindex, nofollow');
  assert.match(admin.headers.get('content-security-policy'), /script-src 'self'/);
  const workspace = await admin.text();
  assert.match(workspace, /data-folder="live"/); assert.match(workspace, /data-folder="drafts"/); assert.match(workspace, /data-folder="archived"/);
  assert.match(workspace, /id="new-post"[^>]*>Write/); assert.match(workspace, /id="post-body"/);
  assert.doesNotMatch(workspace, /href="\/write"|id="posts-dialog"|<select id="visibility"/);
  assert.match(workspace, /<dialog id="publish-dialog"[\s\S]*name="visibility"/);
  const publicIndex = await fetch(`${origin}/blog/`).then(r => r.text());
  assert.doesNotMatch(publicIndex, /post-folders|post-body|new-post|publish-dialog/);
  const send = async (route, value, extra = {}) => fetch(`${origin}/api/${route}`, { method: 'POST', headers: { ...headers, ...extra }, body: JSON.stringify(value) });
  const post = { title: 'Private test', body: '## Notes\n\nSecret text.' };
  assert.equal((await send('save', post, { Origin: 'https://example.com' })).status, 403);
  assert.equal((await send('save', post, { 'X-Writing-Token': 'wrong' })).status, 403);
  let draft = await send('save', post).then(r => r.json());
  assert.equal(draft.post.date, undefined);
  assert.match(await readFile(path.join(directory, 'drafts/private-test.md'), 'utf8'), /draft: true/);
  await assert.rejects(access(path.join(blogRoot, 'private-test.html')));
  const stale = { ...draft.post, title: 'Stale' };
  draft = await send('save', { ...draft.post, body: 'Updated secret.' }).then(r => r.json());
  assert.equal((await send('save', stale)).status, 409);
  const published = await send('publish', { ...draft.post, visibility: 'private' }).then(r => r.json());
  assert.equal(published.post.visibility, 'private'); assert.match(published.post.date, /^\d{4}-\d{2}-\d{2}$/);
  assert.equal((await fetch(origin + published.url, { redirect: 'manual' })).status, 303);
  assert.match(await fetch(origin + published.url, { headers }).then(r => r.text()), /Updated secret/);
  assert.doesNotMatch(await fetch(origin + '/blog/').then(r => r.text()), /Private test/);
  assert.equal((await fetch(origin + '/blog/private-test.html')).status, 404);
  assert.equal((await fetch(origin + '/blog/_content/sample-post.md')).status, 404);
  assert.equal((await fetch(origin + '/blog/scripts/auth.mjs')).status, 404);
  const publicPost = await send('publish', { title: 'Public test', body: 'Readable.', visibility: 'public', date: '1999-01-01' }).then(r => r.json());
  assert.notEqual(publicPost.post.date, '1999-01-01');
  assert.match(await fetch(origin + publicPost.url).then(r => r.text()), /Readable/);
  assert.equal(publicPost.post.readOnly, true);
  assert.equal((await send('save', { ...publicPost.post, body: 'Unpublished changes.' })).status, 409);
  assert.equal((await send('publish', { ...publicPost.post, body: 'Revised.', visibility: 'public' })).status, 409);
  assert.match(await fetch(origin + publicPost.url).then(r => r.text()), /Readable/);
  assert.equal((await send('archive', publicPost.post, { 'X-Writing-Token': 'wrong' })).status, 403);
  assert.equal((await fetch(origin + '/api/archive')).status, 401);
  const deleted = await send('archive', publicPost.post).then(r => r.json());
  assert.equal(deleted.post.archived, true);
  assert.equal((await fetch(origin + publicPost.url)).status, 404);
  assert.doesNotMatch(await fetch(origin + '/blog/').then(r => r.text()), /Public test/);
  assert.match(await readFile(path.join(directory, 'archive/public-test/post.md'), 'utf8'), /Readable/);
  const archives = await fetch(origin + '/api/archive', { headers }).then(r => r.json());
  assert.equal(archives[0].slug, 'public-test');
  const restored = await send('restore', deleted.post).then(r => r.json());
  assert.equal(restored.post.readOnly, true);
  assert.match(await fetch(origin + publicPost.url).then(r => r.text()), /Readable/);
  assert.equal((await send('save', restored.post)).status, 409);
  const privateArchive = await send('archive', published.post).then(r => r.json());
  assert.equal((await fetch(origin + published.url, { headers })).status, 404);
  const privateRestore = await send('restore', privateArchive.post).then(r => r.json());
  assert.equal(privateRestore.post.visibility, 'private');
  assert.equal((await fetch(origin + published.url, { redirect: 'manual' })).status, 303);
  const legacy = (await fetch(origin + '/api/posts', { headers }).then(r => r.json())).find(post => post.slug === 'sample-post');
  await send('archive', legacy);
  for (const url of ['/blog/sample-post.html', '/blog//sample-post.html', '/BLOG/SAMPLE-POST.HTML']) assert.equal((await fetch(origin + url)).status, 404);
  await send('logout', {});
  assert.equal((await fetch(origin + '/api/posts', { headers })).status, 401);
  const second = await fetch(origin + '/api/auth?login=1'); const info = await second.json(); assert.equal(info.setup, false);
  const wrong = await fetch(origin + '/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: second.headers.get('set-cookie').split(';')[0], 'X-Writing-Token': info.token }, body: JSON.stringify({ password: 'wrong password' }) });
  assert.equal(wrong.status, 401);
  assert.doesNotMatch(await readFile(path.join(directory, '.admin-password'), 'utf8'), /Temporary test/);
});
